<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PostController;

Route::get('/', function () {
    return redirect()->route('login');
});

// Since standard Auth::routes() is usually generated by laravel/ui, 
// we assume it is generated or we use Breeze. 
// For now, if ui is not installed, we can fall back to standard Laravel routes.
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('posts', PostController::class);
});

Route::get('/home', function() {
    return redirect()->route('dashboard');
})->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
